// Generated by `npm run i18n:extract`. Do not edit manually.

export const localeConfigs = [
  {
    'id': 'en',
    'tag': 'en',
    'displayName': 'English',
    'direction': 'ltr',
    'search': 'english',
    'enabled': true
  },
  {
    'id': 'zh',
    'tag': 'zh-Hans',
    'displayName': '中文',
    'direction': 'ltr',
    'search': 'cjk',
    'enabled': true
  }
] as const;

export const languages = ['en', 'zh'] as const;
export const sourceLanguage = 'zh' as const;
export const defaultLanguage = 'en' as const;

export type Locale = (typeof languages)[number];
export type LocaleConfig = (typeof localeConfigs)[number];

export function isLocale(value: string): value is Locale {
  return (languages as readonly string[]).includes(value);
}

export function getLocaleConfig(locale: string): LocaleConfig {
  return localeConfigs.find((item) => item.id === locale) ?? localeConfigs[0];
}
