import { createHash } from 'node:crypto';
import { readFile, readdir, mkdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { unified } from 'unified';
import remarkFrontmatter from 'remark-frontmatter';
import remarkMdx from 'remark-mdx';
import remarkParse from 'remark-parse';
import { parse as parseYaml, parseDocument, stringify as stringifyYaml } from 'yaml';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const contentRoot = path.join(repoRoot, 'content', 'docs');
const localizationRoot = path.join(repoRoot, 'localization');
const xliffRoot = path.join(localizationRoot, 'xliff');
const configPath = path.join(localizationRoot, 'config.yml');
const glossaryPath = path.join(localizationRoot, 'glossary.yml');
const generatedLocalesPath = path.join(repoRoot, 'src', 'lib', 'locales.generated.ts');
const statePath = path.join(localizationRoot, 'state.json');

const parser = unified().use(remarkParse).use(remarkMdx).use(remarkFrontmatter, ['yaml']);

function hash(value, length = 16) {
  return createHash('sha256').update(value).digest('hex').slice(0, length);
}

function normalizePath(value) {
  return value.split(path.sep).join('/');
}

function xmlEscape(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function xmlUnescape(value) {
  return value
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>')
    .replaceAll('&quot;', '"')
    .replaceAll('&apos;', "'")
    .replaceAll('&amp;', '&');
}

async function readYaml(file) {
  return parseYaml(await readFile(file, 'utf8'));
}

async function fileExists(file) {
  try {
    await stat(file);
    return true;
  } catch (error) {
    if (error?.code === 'ENOENT') return false;
    throw error;
  }
}

async function walkFiles(root) {
  const output = [];

  async function visit(directory) {
    const entries = await readdir(directory, { withFileTypes: true });
    entries.sort((a, b) => a.name.localeCompare(b.name));

    for (const entry of entries) {
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) await visit(absolute);
      else output.push(absolute);
    }
  }

  await visit(root);
  return output;
}

function getEnabledLocales(config) {
  return config.locales.filter((locale) => locale.enabled);
}

function buildGeneratedLocales(config) {
  const locales = getEnabledLocales(config);
  const serialized = JSON.stringify(locales, null, 2).replaceAll('"', "'");
  const languageIds = locales.map((locale) => `'${locale.id}'`).join(', ');

  return `// Generated by \`npm run i18n:extract\`. Do not edit manually.\n\nexport const localeConfigs = ${serialized} as const;\n\nexport const languages = [${languageIds}] as const;\nexport const sourceLanguage = '${config.sourceLocale}' as const;\nexport const defaultLanguage = '${config.defaultLocale}' as const;\n\nexport type Locale = (typeof languages)[number];\nexport type LocaleConfig = (typeof localeConfigs)[number];\n\nexport function isLocale(value: string): value is Locale {\n  return (languages as readonly string[]).includes(value);\n}\n\nexport function getLocaleConfig(locale: string): LocaleConfig {\n  return localeConfigs.find((item) => item.id === locale) ?? localeConfigs[0];\n}\n`;
}

function getYamlSegments(source, node, fields, file, risk) {
  const segments = [];
  const firstLineEnd = source.indexOf('\n', node.position.start.offset);
  if (firstLineEnd === -1) return segments;

  const document = parseDocument(node.value, { keepSourceTokens: true });
  for (const field of fields) {
    const scalar = document.get(field, true);
    if (!scalar || !Array.isArray(scalar.range) || typeof scalar.value !== 'string') continue;

    const start = firstLineEnd + 1 + scalar.range[0];
    const end = firstLineEnd + 1 + scalar.range[1];
    segments.push(createSegment({
      file,
      locator: `frontmatter:${field}`,
      kind: 'frontmatter',
      text: scalar.value,
      start,
      end,
      risk,
    }));
  }
  return segments;
}

function createSegment({ file, locator, kind, text, start, end, risk }) {
  return {
    id: `u-${hash(`${file}::${locator}`)}`,
    file,
    locator,
    kind,
    text,
    start,
    end,
    risk,
  };
}

function readRiskFromFrontmatter(source, tree) {
  const yamlNode = tree.children.find((node) => node.type === 'yaml');
  if (!yamlNode) return 'normal';
  const document = parseDocument(yamlNode.value);
  return document.get('translationRisk') === 'high' ? 'high' : 'normal';
}

export function collectMdxSegments(source, file, config) {
  const tree = parser.parse(source);
  const risk = readRiskFromFrontmatter(source, tree);
  const segments = [];

  function visit(node, indexes = []) {
    if (node.type === 'yaml') {
      segments.push(...getYamlSegments(
        source,
        node,
        config.extraction.frontmatterFields,
        file,
        risk,
      ));
      return;
    }

    if (node.type === 'text' && node.value.trim() && node.position?.start?.offset != null) {
      segments.push(createSegment({
        file,
        locator: `text:${indexes.join('.')}`,
        kind: 'text',
        text: node.value,
        start: node.position.start.offset,
        end: node.position.end.offset,
        risk,
      }));
    }

    if (node.type === 'image' && node.alt && node.position?.start?.offset != null) {
      const raw = source.slice(node.position.start.offset, node.position.end.offset);
      const match = raw.match(/^!\[([\s\S]*?)\]/);
      if (match) {
        const relativeStart = raw.indexOf(match[1]);
        segments.push(createSegment({
          file,
          locator: `image-alt:${indexes.join('.')}`,
          kind: 'image-alt',
          text: match[1],
          start: node.position.start.offset + relativeStart,
          end: node.position.start.offset + relativeStart + match[1].length,
          risk,
        }));
      }
    }

    if (node.type === 'mdxJsxAttribute' &&
        config.extraction.jsxAttributes.includes(node.name) &&
        typeof node.value === 'string' &&
        node.position?.start?.offset != null) {
      const raw = source.slice(node.position.start.offset, node.position.end.offset);
      const match = raw.match(/^[^=]+\s*=\s*(["'])([\s\S]*)\1$/);
      if (match) {
        const relativeStart = raw.indexOf(match[2]);
        segments.push(createSegment({
          file,
          locator: `jsx:${node.name}:${indexes.join('.')}`,
          kind: `jsx:${node.name}`,
          text: match[2],
          start: node.position.start.offset + relativeStart,
          end: node.position.start.offset + relativeStart + match[2].length,
          risk,
        }));
      }
    }

    if (!Array.isArray(node.children)) return;
    node.children.forEach((child, index) => visit(child, [...indexes, index]));

    if (Array.isArray(node.attributes)) {
      node.attributes.forEach((attribute, index) => visit(attribute, [...indexes, 'a', index]));
    }
  }

  visit(tree);
  segments.sort((a, b) => a.start - b.start);
  return { tree, risk, segments };
}

function collectMetaSegments(source, file, config) {
  const value = JSON.parse(source);
  const segments = [];
  for (const field of config.extraction.metaFields) {
    if (typeof value[field] !== 'string') continue;
    segments.push(createSegment({
      file,
      locator: `meta:${field}`,
      kind: 'meta',
      text: value[field],
      start: -1,
      end: -1,
      risk: 'normal',
    }));
  }
  return { value, risk: 'normal', segments };
}

async function collectLocaleDocuments(locale, config) {
  const root = path.join(contentRoot, locale);
  if (!(await fileExists(root))) return new Map();

  const documents = new Map();
  const files = await walkFiles(root);
  for (const absolute of files) {
    if (!absolute.endsWith('.mdx') && !absolute.endsWith('meta.json')) continue;
    const relative = normalizePath(path.relative(root, absolute));
    const source = await readFile(absolute, 'utf8');
    const parsed = absolute.endsWith('.mdx')
      ? collectMdxSegments(source, relative, config)
      : collectMetaSegments(source, relative, config);
    documents.set(relative, {
      absolute,
      relative,
      source,
      sourceHash: hash(source, 64),
      ...parsed,
    });
  }
  return documents;
}

function buildSourceXliff(documents, config) {
  const units = [...documents.values()].flatMap((document) => document.segments);
  const files = [...documents.values()].map((document) => {
    const fileUnits = document.segments.map((unit) => `      <unit id="${unit.id}" name="${xmlEscape(unit.locator)}">
        <notes>
          <note category="file">${xmlEscape(unit.file)}</note>
          <note category="kind">${xmlEscape(unit.kind)}</note>
          <note category="risk">${unit.risk}</note>
        </notes>
        <segment>
          <source>${xmlEscape(unit.text)}</source>
        </segment>
      </unit>`).join('\n');
    return `    <file id="f-${hash(document.relative)}" original="${xmlEscape(document.relative)}">
${fileUnits}
    </file>`;
  }).join('\n');

  return {
    units,
    content: `<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="${xmlEscape(config.locales.find((locale) => locale.id === config.sourceLocale).tag)}">
${files}
</xliff>
`,
  };
}

function parseTargetXliff(content) {
  const units = new Map();
  const regex = /<unit\s+id="([^"]+)"[\s\S]*?<source>([\s\S]*?)<\/source>(?:[\s\S]*?<target\s+state="([^"]+)"[^>]*>([\s\S]*?)<\/target>)?[\s\S]*?<\/unit>/g;
  let match;
  while ((match = regex.exec(content))) {
    units.set(match[1], {
      source: xmlUnescape(match[2]),
      state: match[3] ?? 'initial',
      target: match[4] == null ? '' : xmlUnescape(match[4]),
    });
  }
  return units;
}

export function buildTargetXliff(sourceUnits, existingUnits, importedUnits, locale, sourceTag) {
  const files = new Map();

  for (const unit of sourceUnits) {
    const existing = existingUnits.get(unit.id);
    const imported = importedUnits.get(unit.id);
    let target = '';
    let state = 'initial';

    if (existing) {
      target = existing.target;
      state = existing.source === unit.text ? existing.state : 'needs-review';
    } else if (imported?.text != null) {
      target = imported.text;
      state = 'final';
    }

    const list = files.get(unit.file) ?? [];
    list.push({ ...unit, target, state });
    files.set(unit.file, list);
  }

  const fileXml = [...files.entries()].map(([file, units]) => {
    const unitXml = units.map((unit) => `      <unit id="${unit.id}" name="${xmlEscape(unit.locator)}">
        <notes>
          <note category="file">${xmlEscape(unit.file)}</note>
          <note category="kind">${xmlEscape(unit.kind)}</note>
          <note category="risk">${unit.risk}</note>
        </notes>
        <segment>
          <source>${xmlEscape(unit.text)}</source>
          <target state="${unit.state}">${xmlEscape(unit.target)}</target>
        </segment>
      </unit>`).join('\n');
    return `    <file id="f-${hash(file)}" original="${xmlEscape(file)}">
${unitXml}
    </file>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="${xmlEscape(sourceTag)}" trgLang="${xmlEscape(locale.tag)}">
${fileXml}
</xliff>
`;
}

function importedUnitsFromDocuments(documents) {
  const units = new Map();
  for (const document of documents.values()) {
    for (const segment of document.segments) units.set(segment.id, segment);
  }
  return units;
}

export function applyReplacements(source, replacements) {
  let output = source;
  for (const replacement of [...replacements].sort((a, b) => b.start - a.start)) {
    output = `${output.slice(0, replacement.start)}${replacement.value}${output.slice(replacement.end)}`;
  }
  return output;
}

function upsertTranslationMetadata(source, risk, status, sourceHash) {
  if (!source.startsWith('---')) return source;
  const openEnd = source.indexOf('\n');
  const closeStart = source.indexOf('\n---', openEnd + 1);
  if (openEnd === -1 || closeStart === -1) return source;

  const frontmatter = parseYaml(source.slice(openEnd + 1, closeStart)) ?? {};
  frontmatter.translationRisk = risk;
  frontmatter.translationStatus = status;
  frontmatter.translationSourceHash = sourceHash;
  const rendered = stringifyYaml(frontmatter, { lineWidth: 0 }).trimEnd();
  return `---\n${rendered}\n---${source.slice(closeStart + 4)}`;
}

function documentStatus(document, targets) {
  const units = document.segments.map((segment) => targets.get(segment.id));
  if (units.some((unit) => !unit?.target)) return 'stale';
  if (units.every((unit) => unit.state === 'final')) return 'approved';
  if (units.some((unit) => unit.state === 'needs-review' || unit.state === 'initial')) return 'stale';
  return 'translated';
}

function renderMdxDocument(document, targets) {
  const replacements = document.segments.map((segment) => ({
    start: segment.start,
    end: segment.end,
    value: targets.get(segment.id)?.target || segment.text,
  }));
  const translated = applyReplacements(document.source, replacements);
  return upsertTranslationMetadata(
    translated,
    document.risk,
    documentStatus(document, targets),
    document.sourceHash,
  );
}

function renderMetaDocument(document, targets, config) {
  const value = structuredClone(document.value);
  for (const field of config.extraction.metaFields) {
    const segment = document.segments.find((item) => item.locator === `meta:${field}`);
    if (!segment) continue;
    value[field] = targets.get(segment.id)?.target || segment.text;
  }
  return `${JSON.stringify(value, null, 2)}\n`;
}

async function buildArtifacts({ write }) {
  const config = await readYaml(configPath);
  const sourceDocuments = await collectLocaleDocuments(config.sourceLocale, config);
  const sourceLocale = config.locales.find((locale) => locale.id === config.sourceLocale);
  if (!sourceLocale) throw new Error(`Unknown source locale: ${config.sourceLocale}`);

  const sourceXliff = buildSourceXliff(sourceDocuments, config);
  const outputs = new Map([
    [generatedLocalesPath, buildGeneratedLocales(config)],
    [path.join(xliffRoot, `${config.sourceLocale}.xlf`), sourceXliff.content],
  ]);
  const targetUnits = new Map();

  for (const locale of getEnabledLocales(config)) {
    if (locale.id === config.sourceLocale) continue;
    const targetPath = path.join(xliffRoot, `${locale.id}.xlf`);
    const existing = await fileExists(targetPath)
      ? parseTargetXliff(await readFile(targetPath, 'utf8'))
      : new Map();
    const importedDocuments = await collectLocaleDocuments(locale.id, config);
    const imported = importedUnitsFromDocuments(importedDocuments);
    const content = buildTargetXliff(sourceXliff.units, existing, imported, locale, sourceLocale.tag);
    outputs.set(targetPath, content);
    targetUnits.set(locale.id, parseTargetXliff(content));
  }

  const state = {
    sourceLocale: config.sourceLocale,
    defaultLocale: config.defaultLocale,
    documents: Object.fromEntries([...sourceDocuments.values()].map((document) => [
      document.relative,
      {
        sourceHash: document.sourceHash,
        risk: document.risk,
        segments: document.segments.length,
        locales: Object.fromEntries([...targetUnits.entries()].map(([locale, units]) => [
          locale,
          documentStatus(document, units),
        ])),
      },
    ])),
  };
  outputs.set(statePath, `${JSON.stringify(state, null, 2)}\n`);

  if (write) {
    for (const [file, content] of outputs) {
      await mkdir(path.dirname(file), { recursive: true });
      await writeFile(file, content);
    }
  }

  return { config, sourceDocuments, targetUnits, outputs };
}

async function renderArtifacts({ write }) {
  const config = await readYaml(configPath);
  const sourceDocuments = await collectLocaleDocuments(config.sourceLocale, config);
  const outputs = new Map();

  for (const locale of getEnabledLocales(config)) {
    if (locale.id === config.sourceLocale) continue;
    const targetPath = path.join(xliffRoot, `${locale.id}.xlf`);
    if (!(await fileExists(targetPath))) throw new Error(`Missing translation file: ${targetPath}`);
    const targets = parseTargetXliff(await readFile(targetPath, 'utf8'));

    for (const document of sourceDocuments.values()) {
      const rendered = document.relative.endsWith('.mdx')
        ? renderMdxDocument(document, targets)
        : renderMetaDocument(document, targets, config);
      outputs.set(path.join(contentRoot, locale.id, document.relative), rendered);
    }
  }

  if (write) {
    for (const [file, content] of outputs) {
      await mkdir(path.dirname(file), { recursive: true });
      await writeFile(file, content);
    }
  }

  return { config, sourceDocuments, outputs };
}

async function assertFilesMatch(outputs, label) {
  const failures = [];
  for (const [file, expected] of outputs) {
    const relative = normalizePath(path.relative(repoRoot, file));
    if (!(await fileExists(file))) {
      failures.push(`${relative} is missing`);
      continue;
    }
    const actual = await readFile(file, 'utf8');
    if (actual !== expected) failures.push(`${relative} is out of date`);
  }
  if (failures.length) throw new Error(`${label}:\n- ${failures.join('\n- ')}`);
}

async function checkGlossary(config) {
  const glossary = await readYaml(glossaryPath);
  const failures = [];
  for (const locale of getEnabledLocales(config)) {
    if (locale.id === config.sourceLocale) continue;
    const targetPath = path.join(xliffRoot, `${locale.id}.xlf`);
    const content = await readFile(targetPath, 'utf8');
    const units = parseTargetXliff(content);
    for (const term of glossary.terms ?? []) {
      const expected = term.translations?.[locale.id];
      if (!expected) continue;
      for (const unit of units.values()) {
        if (unit.source.includes(term.source) && unit.target && !unit.target.includes(expected)) {
          failures.push(`${locale.id}: "${term.source}" must be translated as "${expected}"`);
        }
      }
    }
  }
  if (failures.length) throw new Error(`Glossary validation failed:\n- ${[...new Set(failures)].join('\n- ')}`);
}

async function checkHighRiskApprovals(config, sourceDocuments) {
  if (process.env.I18N_REQUIRE_APPROVED_HIGH_RISK !== '1') return;
  const failures = [];
  for (const locale of getEnabledLocales(config)) {
    if (locale.id === config.sourceLocale) continue;
    const targetPath = path.join(xliffRoot, `${locale.id}.xlf`);
    const targets = parseTargetXliff(await readFile(targetPath, 'utf8'));
    for (const document of sourceDocuments.values()) {
      if (document.risk !== 'high') continue;
      if (documentStatus(document, targets) !== 'approved') {
        failures.push(`${locale.id}/${document.relative} requires language-review approval`);
      }
    }
  }
  if (failures.length) throw new Error(`High-risk translations are not approved:\n- ${failures.join('\n- ')}`);
}

async function validateRenderedMdx(outputs) {
  for (const [file, content] of outputs) {
    if (!file.endsWith('.mdx')) continue;
    try {
      parser.parse(content);
    } catch (error) {
      throw new Error(`Invalid generated MDX: ${normalizePath(path.relative(repoRoot, file))}`, {
        cause: error,
      });
    }
  }
}

async function checkStructure(config, sourceDocuments) {
  const sourceFiles = new Set(sourceDocuments.keys());
  const failures = [];
  for (const locale of getEnabledLocales(config)) {
    if (locale.id === config.sourceLocale) continue;
    const targetDocuments = await collectLocaleDocuments(locale.id, config);
    const targetFiles = new Set(targetDocuments.keys());
    for (const file of sourceFiles) if (!targetFiles.has(file)) failures.push(`${locale.id}/${file} is missing`);
    for (const file of targetFiles) if (!sourceFiles.has(file)) failures.push(`${locale.id}/${file} has no source counterpart`);
  }
  if (failures.length) throw new Error(`Locale trees are not aligned:\n- ${failures.join('\n- ')}`);
}

async function runCheck() {
  const extracted = await buildArtifacts({ write: false });
  await assertFilesMatch(extracted.outputs, 'Localization extraction check failed');
  const rendered = await renderArtifacts({ write: false });
  await assertFilesMatch(rendered.outputs, 'Rendered translation check failed');
  await validateRenderedMdx(rendered.outputs);
  await checkStructure(extracted.config, extracted.sourceDocuments);
  await checkGlossary(extracted.config);
  await checkHighRiskApprovals(extracted.config, extracted.sourceDocuments);
  console.log('Localization files are synchronized and valid.');
}

async function main() {
  const command = process.argv[2];
  if (command === 'extract') {
    await buildArtifacts({ write: true });
    console.log('Updated locale configuration and XLIFF files.');
    return;
  }
  if (command === 'render') {
    await renderArtifacts({ write: true });
    console.log('Rendered translated MDX and navigation files.');
    return;
  }
  if (command === 'check') {
    await runCheck();
    return;
  }
  if (command === 'sync') {
    await buildArtifacts({ write: true });
    await renderArtifacts({ write: true });
    await runCheck();
    return;
  }
  throw new Error('Usage: node scripts/i18n.mjs <extract|render|check|sync>');
}

if (path.resolve(process.argv[1] ?? '') === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
